config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users
  resources :projects
  
  root 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
        can :manage, :all
    else can :read, :all
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, except: [:index, :new, :create]

  def index
    @projects = Project.all.sort_by {|p| p.name}
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: "Project has been created."
    else
      flash[:alert] = "Project has not been added."
      render :new
    end
  end

  def show; end

  def update; end

  def delete; end

  def find_project
    @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking for could not be found."
      redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/dashboard/index.html.haml
%h2 Dashboard
%br
= link_to 'Make a Ticket>>', projects_path, id: 'link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Project Gage
    /[if IE]
      %script{:type => "text/javascript", :src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
  %body{ data: { controller: "#{controller_name}", action: "#{action_name}" } }
    .fixed
      %nav.top-bar
        %ul.title-area
          %li.name
            = link_to image_tag('gs_logo.png'), root_path, id: 'logo'
          %li.toggle-topbar
            %a{ href: "#"}
        %section.top-bar-section
          %ul.right
            %li
              = link_to 'Dashboard', root_path
    .container
      .row
        .twelve.columns
          #flash
            - flash.each do |name, msg|
              %div{class: "alert-box #{name == :notice ? "success" : "alert"}"}
                %a{class: "close", href: "#"} &times
                = msg
      .row
        = yield
        %footer

app/views/projects/_form.html.haml
= simple_form_for @project do |f|
  = f.input :name, label: 'Name'
  = f.input :description, label: 'Description'
  = f.submit :button

app/views/projects/_list_projects.html.haml
%ul
  - @projects.each do |project|
    %li
      = link_to project.name, project_path(project)

app/views/projects/index.html.haml
%h2 Tickets
%br
= render 'list_projects'
%br
= link_to 'Create New Ticket>>', new_project_path

app/views/projects/new.html.haml
%h4 New Ticket
%br 
= render 'form'

app/views/projects/show.html.haml
%h3= @project.name
%br 
%span Description:
= @project.description